@startmindmap
<style>

legend {
  Padding 20
}

</style>

skinparam topurl StructureDefinition-

legend left
<b>The legend:</b>

- Background color: <b><color:#EEEEAE>yellow</color></b> - <b>Main</b>: CZ Imaging Order Examination root elements.
- Background color: <b><color:#TECHNOLOGY>green</color></b> - <b>Common</b>: Common elements of CZ Order.
- Background color: <b><color:#APPLICATION>blue</color></b> - <b>Specific</b>: Specific elements of CZ Imaging Order.
end legend

*[#EEEEAE] [[BodyImageOrderCz.html Imaging Order Body]]
**[#TECHNOLOGY] [[ImageOrderInformationCz.html Order information]]
***_ Order Details
***_ Order Reason
**[#TECHNOLOGY] [[ClinicalEventCz.html Clinical Event]]
**[#TECHNOLOGY] [[ImageAppointmentCz.html Appointment]]
**[#TECHNOLOGY] [[SpecimenInformationCz.html Specimen Information]]
**[#TECHNOLOGY] [[CoverageBodyCz.html Additional Coverage]]
**[#APPLICATION] [[ImageSupportingInformationCz.html Supporting Information]]
***_ Biometric Data
***_ Weight
***_ Height
***_ Urgent Information
****_ Allergy Intolerance
****_ Warnings
***_ Medication
***_ Implant
***_ Limitation of Patient Mobility
***_ Other Relevant Clinical Information
***_ Other Information
**[#APPLICATION] [[OrderDataElementsCz.html Order Data]]
***_ Examination Code
***_ Name of the Examination
***_ Modality
***_ Body Part
***_ Laterality
***_ Note
**[#APPLICATION] [[PlannedCareOrdersCz.html Planned Care Orders]]
**[#APPLICATION] [[OtherSupportingInformationCz.html Other Supporting Information]]
@endmindmap