@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend

class "Presented Form" <<LogicalModel>> [[StructureDefinition-PresentedFormCz.html]]
note top #EEEEAE [[ConceptMap-AttachmentImagingOrder2FHIR-cz.html]]
Concept Map
endnote

class "Attachments" <<LogicalModel>> [[StructureDefinition-AttachmentsCz.html]]
note top #EEEEAE [[ConceptMap-AttachmentImagingOrder2FHIR-cz.html]]
Concept Map
endnote

class "cz-compositionImageOrder.extension:presentedForm" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/img-order/StructureDefinition-cz-compositionImageOrder.html#ac]]
class "cz-attachment" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/img-order/StructureDefinition-cz-attachment.html]]

"Presented Form" -- "Attachments"

"Presented Form" <|. "cz-compositionImageOrder.extension:presentedForm"
"Attachments" <|. "cz-attachment"

"Presented Form" -r[hidden]-> "Attachments"
"Presented Form" -d[hidden]-> "cz-compositionImageOrder.extension:presentedForm"
"Attachments" -d[hidden]-> "cz-attachment"

@enduml
