@startmindmap
skinparam topurl StructureDefinition-

*[#EEEEAE] [[logHeaderImagingOrder.html Hlavička obrazové žádanky]]
**[#TECHNOLOGY] [[logSubjectCz.html Identifikace pacienta]]
/'    Shell we keep or not?
** Preferred Health Professional
'/
**[#TECHNOLOGY] [[logPayerCz.html Zdravotní pojištění]]
/' ***_ Health insurance code
***_ Health insurance name
***_ Health insurance number '/
**[#TECHNOLOGY] [[logCoverageOrderCz.html Úhrada]]
/'
** Attestation
***_ Attester
***_ DateTime
** Legal authentication
***_ Legal authenticator
***_ DateTime
'/
**[#TECHNOLOGY] [[logDocumentMetadataCz.html Metadata dokumentu]]
***_ ID dokumentu
***_ Kategorie dokumentu
***_ Stav žádanky
***_ Datum a čas vytvoření
***_ Název dokumentu
***_ Správce dokumentu
***_ Důvěrnost dokumentu
***_ Jazyk dokumentu
***_ Verze dokumentu
**[#TECHNOLOGY] [[logAuthorCz.html Objednatel]]
**[#TECHNOLOGY] [[logRequestedPerformerCz.html Zpracovatel]]
**[#TECHNOLOGY] [[logAdditionalRecipientCz.html Příjemce nálezu]]
**[#TECHNOLOGY] [[logdigitalSignatureCz.html Elektronické podpisy]]
***_ Elektronický podpis nebo pečeť dokumentu
***_ Časové razítko
/' ** Intended recipient
** Authorship
***_ Author
***_ DateTime
** Attestation
***_ Attester
***_ DateTime
** Legal authentication
***_ Legal authenticator
***_ DateTime
** Document metadata
***_ Document ID
***_ Document type
***_ Document status
***_ Period
***_ Report date and time
***_ Document title
***_ Event type
***_ Specialty
***_ Report custodian
***_ Document format
***_ Confidentiality
***_ Language
***_ Version
***_ Study Instance UID
***_ Accession number '/
@endmindmap