@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logický model |
| <#TECHNOLOGY>  Profil |
endlegend
class "Tělo žádanky obrazového vyšetření" <<LogicalModel>> [[StructureDefinition-BodyImageOrderCz.html]]
note top #EEEEAE [[ConceptMap-BodyImagingOrder2FHIR-cz.html]]
Concept Mapa
endnote

class "cz-imagingOrderInformation" <<Profile>> [[StructureDefinition-cz-imagingOrderInformation.html]]
class "cz-conditionImage" <<Profile>> [[StructureDefinition-cz-conditionImage.html]]
class "cz-encounter" <<Profile>> [[StructureDefinition-cz-encounter.html]]
class "cz-coverage" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-coverage.html]]
class "cz-appointment" <<Profile>> [[StructureDefinition-cz-appointment.html]]
class "cz-specimen" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-specimen.html]]
class "cz-observationImage" <<Profile>> [[StructureDefinition-cz-observationImage.html]]
class "cz-bodyweight" <<Profile>> [[StructureDefinition-cz-bodyweight.html]]
class "cz-bodyheight" <<Profile>> [[StructureDefinition-cz-bodyheight.html]]
class "cz-MedicationStatement" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-MedicationStatement.html]]
class "cz-deviceUseStatement" <<Profile>> [[StructureDefinition-cz-deviceUseStatement.html]]
class "cz-allergyIntolerance" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/cz-core/StructureDefinition-cz-allergyIntolerance.html]]
class "cz-carePlanImage" <<Profile>> [[StructureDefinition-cz-carePlanImage.html]]

"Tělo žádanky obrazového vyšetření" <|. "cz-imagingOrderInformation"
"Tělo žádanky obrazového vyšetření" <|. "cz-appointment"
"Tělo žádanky obrazového vyšetření" <|. "cz-coverage"
"Tělo žádanky obrazového vyšetření" <|. "cz-conditionImage"
"Tělo žádanky obrazového vyšetření" <|. "cz-encounter"
"Tělo žádanky obrazového vyšetření" <|. "cz-specimen"
"Tělo žádanky obrazového vyšetření" <|. "cz-observationImage"
"Tělo žádanky obrazového vyšetření" <|. "cz-bodyweight"
"Tělo žádanky obrazového vyšetření" <|. "cz-bodyheight"
"Tělo žádanky obrazového vyšetření" <|. "cz-MedicationStatement"
"Tělo žádanky obrazového vyšetření" <|. "cz-deviceUseStatement"
"Tělo žádanky obrazového vyšetření" <|. "cz-allergyIntolerance"
"Tělo žádanky obrazového vyšetření" <|. "cz-carePlanImage"

"cz-imagingOrderInformation" -d[hidden]-> "cz-encounter"
"cz-encounter" -d[hidden]-> "cz-conditionImage"
"cz-conditionImage" -d[hidden]-> "cz-appointment"
"cz-appointment" -d[hidden]-> "cz-coverage"
"cz-coverage" -d[hidden]-> "cz-specimen"
"cz-specimen" -d[hidden]-> "cz-observationImage"
"cz-observationImage" -d[hidden]-> "cz-bodyweight"
"cz-bodyweight" -d[hidden]-> "cz-bodyheight"
"cz-bodyheight" -d[hidden]-> "cz-MedicationStatement"
"cz-MedicationStatement" -d[hidden]-> "cz-deviceUseStatement"
"cz-deviceUseStatement" -d[hidden]-> "cz-allergyIntolerance"
"cz-allergyIntolerance" -d[hidden]-> "cz-carePlanImage"

@enduml
