Logical: LogCzImageSupportingInformationCz
Id: logImageSupportingInformationCz
Title: "A.3.1 - Klinické informace"
Description: """Informace a údaje sdělované pracovišti zobrazovacích metod, mající vliv na provedení objednávky či interpretaci výsledků vyšetření"""

* insert SetFmmandStatusRule ( 0, draft )

*  biometrickaData 1..1 Base "A.3.1.1 - Biometrické údaje" """"""
*  biometrickaData.vaha 1..1 Base "A.3.1.1.1 - Váha" """Váha subjektu"""
*  biometrickaData.vaha.hodnota 1..1 Quantity "A.3.1.1.1.1 - Hodnota" """Hodnota údaje včetně jednotky měření."""
*  biometrickaData.vaha.kod 1..1 CodeableConcept "A.3.1.1.1.2 - Kód" """Kód pozorování identifikující význam údaje váha"""
*  biometrickaData.vaha.datumACas  0..1 dateTime "A.3.1.1.1.3 - Datum" """Datum zjištění údaje, uvádí se, pokud je odlišné od data vystavení objednávky."""
*  biometrickaData.vyska 1..1 Base "A.3.1.1.2 - Výška" """Výška subjektu"""
*  biometrickaData.vyska.hodnota 1..1 Quantity "A.3.1.1.2.1 - Hodnota" """Hodnota údaje včetně jednotky měření."""
*  biometrickaData.vyska.kod 1..1 CodeableConcept "A.3.1.1.2.2 - Kód" """Kód pozorování identifikující význam údaje výška"""
*  biometrickaData.vyska.datumACas  0..1 dateTime "A.3.1.1.2.3 - Datum" """Datum zjištění údaje, uvádí se, pokud je odlišné od data vystavení objednávky.""" 
*  dalsiRelevantniUdaje 0..1 Base "A.3.1.2 - Další relevantní klinické informace" """Další relevantní klinické informace"""
*  dalsiRelevantniUdaje.kod 0..* CodeableConcept "A.3.1.2.1 - Popis problému / diagnózy / stavu" """Diagnózy a dalších klinických informací mající vliv na průběh či výsledek vyšetření či jeho interpretaci (např. srdeční selhávání, klaustrofobie, renální selhání)""" 
*  dalsiRelevantniUdaje.text 0..1 string "A.3.1.2.2 - Klinické informace volným textem" """Klinické informace nezbytné pro správné provedení objednávky či interpretaci výsledků."""
*  kontradikce 0..* Base "A.3.1.3 - Možné kontraindikace vyšetření nebo podání k.l." """vyjma alergie a varování které jsou v sekci níže"""
*  kontradikce.medikace 0..* Base "A.3.1.3.1 - Medikace" """Blok medikace obsahující informace o medikaci mající vliv na průběh či výsledek vyšetření či jeho interpretaci."""
*  kontradikce.medikace.id 0..* Identifier "A.3.1.3.1.1 - ID medikace" """ID medikace"""
*  kontradikce.medikace.kod 0..* code "A.3.1.3.1.2 - Kod medikace" """Kod medikace"""
*  kontradikce.medikace.mnozstvi 0..1 Ratio "A.3.1.3.1.3 - Mnozstvi" """Mnozstvi medikace"""
*  implantat 0..* Base "A.3.1.4 - Implantat" """Seznam implantátů či pomůcek majících vliv na průběh vyšetření či jeho interpretaci."""
*  implantat.typ 1..1 CodeableConcept "A.3.1.4.1 - Druh implantátu" """Druh implantátu"""
*  implantat.id 0..* Identifier "A.3.1.4.2 - ID implantátu" """Normalizovaný identifikátor, např. UDI, dle nařízení EU 2017/745, kód ZP dle katalogu zdravotní pojišťovny"""
*  implantat.model 1..1 string "A.3.1.4.3 - Konkrétní model" """Konkrétní model"""
*  implantat.castTela 0..* CodeableConcept "A.3.1.4.4 - Část těla" """Část těla, kam je implantován"""
*  urgentniInformace 0..1 Base "A.3.1.5 - Urgentní informace" """Blok urgentní informace ve stejné struktuře jako v ostatních typech dokumentů (propouštěcí zpráva, pacientský souhrn)"""
*  urgentniInformace.allergie 1..* Base "A.3.1.5.1 - Alergie a intolerance" """Alergie a intolerance, které mohou ovlivnit realizaci objednávky či interpretaci výsledků."""
*  urgentniInformace.varovani 0..* string "A.3.1.5.2 - Varování" """Varování a upozornění, která mohou vlivní realizaci objednávky či interpretaci výsledků."""
*  omezeniPohyblivostiPacienta 1..1 Base "A.3.1.6 - Omezení pohyblivosti pacienta" """Omezení pohyblivosti pacienta"""
*  dalsiUdaje 0..* Base "A.3.1.7 - Další formalizované údaje" """Další formalizované údaje sdělované provádějícímu pracovišti"""
*  dalsiUdaje.datumACas 0..1 dateTime "A.3.1.7.1 - Datum" """Datum zjištění údaje, uvádí se, pokud je odlišné od data vystavení objednávky."""
*  dalsiUdaje.kod 1..1 CodeableConcept "A.3.1.7.2 - Kód" """Kód pozorování identifikující význam údaje (týden gravidity apod.)."""
*  dalsiUdaje.hodnota 0..1 Quantity "A.3.1.7.3 - Hodnota" """Hodnota údaje včetně jednotky měření."""
