Logical: LogEnImageSupportingInformationCz
Id: ImageSupportingInformationCz
Title: "A.3.1 - Supporting Information"
Description: """Supporting Information - Information and data communicated by the imaging methods department that has an impact on the execution of the order or the interpretation of the examination results"""

* insert SetFmmandStatusRule ( 0, draft )

*  biometricData 1..1 Base "A.3.1.1 - Bimetric Data" """If the required clinical data are available, it is mandatory."""
*  biometricData.weight 1..1 Base "A.3.1.1.1 - Weight" """Subject weight"""
*  biometricData.weight.valueQuantity 1..1 Quantity "A.3.1.1.1.1 - Weight value" """Data value including unit of measurement."""
*  biometricData.weight.code 1..1 CodeableConcept "A.3.1.1.1.2 - Weight code" """Observation code identifying the meaning of the weight data"""
*  biometricData.weight.dateTime  0..1 dateTime "A.3.1.1.1.3 - Weight date and time" """The date of weight discovery is stated if it is different from the date of order issuance."""
*  biometricData.height 1..1 Base "A.3.1.1.2 - Height" """Subject height"""
*  biometricData.height.valueQuantity 1..1 Quantity "A.3.1.1.2.1 - Height value" """Data value including unit of measurement."""
*  biometricData.height.code 1..1 CodeableConcept "A.3.1.1.2.2 - Height code" """Observation code identifying the meaning of the height data"""
*  biometricData.height.dateTime  0..1 dateTime "A.3.1.1.2.3 - Height date and time" """The date of height discovery is stated if it is different from the date of order issuance.""" 
*  otherRelevantClinicalInformation 0..1 Base "A.3.1.2 - Other relevant clinical information" """Other relevant clinical information"""
*  otherRelevantClinicalInformation.code 0..* CodeableConcept "A.3.1.2.1 - Code of other information" """Diagnoses and other clinical information that may affect the course or result of the examination or its interpretation (e.g. heart failure, claustrophobia, renal failure)""" 
*  otherRelevantClinicalInformation.text 0..1 string "A.3.1.2.2 - Text of other information" """Clinical information necessary for correct order execution or interpretation of results."""
*  contraindication 0..* Base "A.3.1.3 - Contraindication" """Possible contraindications for examination except for allergies and warnings which are in the section below"""
*  contraindication.medication 0..* Base "A.3.1.3.1 - Medication" """Medication block containing information about medication that has an impact on the course or result of the examination or its interpretation."""
*  contraindication.medication.identifier 0..* Identifier "A.3.1.3.1.1 - Medication identifier" """Identifier of medication"""
*  contraindication.medication.code 0..* code "A.3.1.3.1.2 - Medication code" """Code of medication"""
*  contraindication.medication.amount 0..1 Ratio "A.3.1.3.1.3 - Ratio" """Amount of drug in package"""
*  implant 0..* Base "A.3.1.4 - Implant" """List of implants or devices that affect the course of the examination or its interpretation."""
*  implant.type 1..1 CodeableConcept "A.3.1.4.1 - Implant type" """Type of implant"""
*  implant.identifier 0..* Identifier "A.3.1.4.2 - Implant identifier" """Standardized identifier, e.g. UDI, according to EU Regulation 2017/745, ZP code according to the health insurance company catalog"""
*  implant.model 1..1 string "A.3.1.4.3 - Implant model" """Specifies a specific model"""
*  implant.bodyPart 0..* CodeableConcept "A.3.1.4.4 - Body part" """Body part where it is implanted"""
*  urgentInformation 0..1 Base "A.3.1.5 - Urgent information" """Urgent information block in the same structure as in other types of documents (discharge report, patient summary)"""
*  urgentInformation.allergyIntolerance 1..* Base "A.3.1.5.1 - Allergy intolerance" """Allergies and intolerances that may affect order fulfillment or interpretation of results"""
*  urgentInformation.warnings 0..* string "A.3.1.5.2 - Warning" """Warnings and notices that may affect order fulfillment or interpretation of results"""
*  limitationOfPatientMobility 1..1 Base "A.3.1.6 - Limitation of patient mobility" """Describes the patient's mobility limitations"""
*  otherInformation 0..* Base "A.3.1.7 - Other information" """Other formalized observation communicated to the implementing workplace"""
*  otherInformation.dateTime 0..1 dateTime "A.3.1.7.1 - Date and time of information" """Date of information discovery, stated if different from the date of order"""
*  otherInformation.code 1..1 CodeableConcept "A.3.1.7.2 - Code of information" """Observation code identifying the meaning of the observation (week of gestation, etc.)"""
*  otherInformation.value 0..1 Quantity "A.3.1.7.3 - Value of information" """Observation value including unit of measurement."""
